name = "cognizo-cf-worker"
main = "build/index.js"
compatibility_date = "2025-10-14"
workers_dev = false
preview_urls = false

[build]
command = "./build.sh"


[vars]
TRAFFIC_ANALYTICS_API_URL = "https://traffic-analytics.cognizo.ai"
TRACKING_CODE = "1120a937966abd3c6033063f6b53df0afb8e71c260277e1f760b5cda69507df1"
# EXCLUDE_PATHS = ""  # Uncomment to exclude custom paths

[observability]
[observability.logs]
enabled = true
head_sampling_rate = 1
invocation_logs = true